import Head from "next/head";
import Homepage from "../views/Home/Homepage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Online youtube downloader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Homepage />
    </div>
  );
}
